repos:
  # Common sanity checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=512, --enforce-all]
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace


  # Python linters & formatters
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.3
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  # C++ linters & formatters
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: 336fdd7
    hooks:
      - id: clang-format
        args: [-i, -style=file]
      - id: clang-tidy
        args: [--fix, -p=packages/build]
