services:
  handy:
    image: registry.robotics-lab.ru/handy:0.8.0
    container_name: "${CONTAINER_NAME:-handy-${USER}}"
    networks: [default]
    privileged: true
    stdin_open: true
    runtime: ${DOCKER_RUNTIME:-runc}
    entrypoint: "/bin/bash -c 'trap : TERM INT; sleep infinity & wait'"
    working_dir: "/handy"
    build:
      dockerfile: Dockerfile
      context: .
      x-bake:
        platforms:
          # - linux/arm64
          - linux/amd64
        cache-from:
          - type=registry,ref=registry.robotics-lab.ru/handy:cache-arm64
          - type=registry,ref=registry.robotics-lab.ru/handy:cache-amd64
        cache-to:
          # [!!!] Warning: https://github.com/docker/buildx/discussions/1382
          # - type=registry,mode=max,ref=registry.robotics-lab.ru/handy:cache-arm64
          - type=registry,mode=max,ref=registry.robotics-lab.ru/handy:cache-amd64
    ports:
      - "${FOXGLOVE_PORT:-8765}:8765"
    volumes:
      - "${PWD}:/handy"
      - "/dev:/dev"

networks:
  default:
    name: "${CONTAINER_NAME:-handy-${USER}}"
