version: "3"

services:
  handy:
    container_name: "${NAME:-handy-${USER}}"
    image: registry.robotics-lab.ru/handy:0.6.0
    stdin_open: true
    tty: true
    build:
      dockerfile: Dockerfile
      context: .
      tags:
          - "registry.robotics-lab.ru/handy:latest"
          - "registry.robotics-lab.ru/handy:0.6.0"
      x-bake:
        platforms: [linux/arm64, linux/amd64]
        output: "type=image,name=registry.robotics-lab.ru/handy:latest,push=true,compression=zstd"
        cache-to: "type=registry,ref=registry.robotics-lab.ru/handy:cache,mode=max,compression=zstd"
        cache-from: "type=registry,ref=registry.robotics-lab.ru/handy:cache"
    ports:
      - "${FOXGLOVE_PORT:-8765}:8765"
    runtime: ${DOCKER_RUNTIME:-runc}
    volumes:
      - "${PWD}:/handy"
