version: "3.9"
services:
  handy:
    container_name: "${CONTAINER_NAME:-handy-${USER}}"
    image: registry.robotics-lab.ru/handy:0.7.0
    privileged: true
    stdin_open: true
    runtime: ${DOCKER_RUNTIME:-runc}
    entrypoint: "/bin/bash -c 'trap : TERM INT; sleep infinity & wait'"
    working_dir: "/handy"
    build:
      dockerfile: Dockerfile
      context: .
      tags:
          - "registry.robotics-lab.ru/handy:latest"
          - "registry.robotics-lab.ru/handy:0.7.0"
      x-bake:
        platforms: [linux/arm64, linux/amd64]
        cache-to: "type=registry,ref=registry.robotics-lab.ru/handy:cache,mode=max"
        cache-from: "type=registry,ref=registry.robotics-lab.ru/handy:cache"
    networks:
      - default
    ports:
      - "${FOXGLOVE_PORT:-8765}:8765"
    volumes:
      - "${PWD}:/handy"
      - "/dev:/dev"
networks:
  default:
    name: "${CONTAINER_NAME:-handy-${USER}}"
