version: "3.5"

services:
  handy-amd64:
    container_name: handy-amd64
    image: cr.yandex/crp8hpfj5tuhlaodm4dl/handy:amd64-0.2.0
    stdin_open: true
    tty: true
    build:
      dockerfile: docker/handy-amd64.dockerfile
      context: .
    network_mode: "host"
    volumes:
      - "${HOME}/handy:/handy"

  handy-jetson:
    container_name: handy-jetson
    image: cr.yandex/crp8hpfj5tuhlaodm4dl/handy:jetson-0.2.0
    stdin_open: true
    privileged: true
    tty: true
    build:
      dockerfile: docker/handy-jetson.dockerfile
      context: .
    ports:
    - "9090:9090"
    - "8765:8765"
    volumes:
      - "${HOME}/handy:/handy"
