name: Codestyle Check

on:
  pull_request:
    branches: [ "master" ]
    types: [ opened, reopened, ready_for_review, synchronize ]

jobs: 
  code-style:
    name: Code Style Check
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install flake8 yamllint
          sudo apt-get update
          sudo apt-get install -y clang-format findutils

      - name: Check Python code style
        run: flake8 . --exclude=venv,build,log,install --statistics

      - name: Format check C++
        if: always()
        run: |
          find . -type f \( -name "*.cpp" -o -name "*.h" -o -name "*.hpp" \) -not -path "*/install/*" -not -path "*/log/*" -not -path "*/build/*" | xargs clang-format -i --dry-run --Werror
        
      - name: "Fail if any checks failed"
        if: failure()
        run: exit 1
