name: Codestyle Check

on:
  pull_request:
    branches: [ "master" ]
    types: [ opened, reopened, ready_for_review, synchronize ]

env:
  SKIP: "clang-tidy"

jobs: 
  code-style:
    env:
      check_changed_only: true

    name: Code Style Check
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Fetch base branch
        run: git fetch origin ${{ github.event.pull_request.base.ref }}:${{ github.event.pull_request.base.ref }};
      
      - name: Launching pre-commit
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --from-ref ${{ github.event.pull_request.base.sha }} --to-ref ${{ github.sha }}
