name: ROS2 CI

on:
  pull_request:
    branches: [ "master" ]
    types: [ opened, reopened, ready_for_review, synchronize ]

  workflow_dispatch:
    inputs:
      check_all_files:
        description: 'Flag whether to lint all files'
        required: false
        default: true
        type: boolean

env:
  CHECK_ALL_FILES: ${{ github.event.inputs.check_all_files || 'false' }}

jobs:
  extract-image:
    name: Extraction of configs
    runs-on: ubuntu-latest
    outputs:
      image-url: ${{ steps.extractor.outputs.image_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract image URL
        id: extractor
        run: |
          IMAGE_URL=$(grep -o 'image:\s*[^ ]*' docker-compose.yaml | cut -d ' ' -f2)
          echo "image_url=$IMAGE_URL" >> $GITHUB_OUTPUT
          echo $IMAGE_URL

  build-and-check:
    name: Building, testing, linting
    needs: extract-image
    runs-on: self-hosted

    container:
      image: ${{ needs.extract-image.outputs.image-url}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build ROS2 packages
        shell: bash
        run: |
          source $ROS_ROOT/setup.bash
          cd $GITHUB_WORKSPACE/packages
          mkdir -p camera/params
          colcon build --merge-install --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DCMAKE_TOOLS_ADDRESS_SANITIZER=1
          source install/setup.bash

      - name: Test ROS2 packages
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE/packages
          colcon test --ctest-args tests --merge-install --executor parallel --parallel-workers $(nproc) --return-code-on-test-failure

      - name: Fetch PR base branch
        shell: bash
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          git fetch origin ${{ github.event.pull_request.base.ref }}:${{ github.event.pull_request.base.ref }}

      - name: Lint changed files only
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: clang-tidy --from-ref ${{ github.event.pull_request.base.sha }} --to-ref ${{ github.sha }}

      - name: Lint all files
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.check_all_files }}
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: clang-tidy --all-files
